---

###
# DEBIAN
###

# Package name
puppet_server_package_name: puppetserver={{ puppet_server_version }}*
puppet_agent_package_name: puppet-agent={{ puppet_agent_version }}*

# DEB URL
puppet_apt_deb: https://apt.puppetlabs.com/puppet{{ puppet_major_version }}-release-{{ ansible_distribution_release }}.deb
puppet_apt_key: https://apt.puppetlabs.com/DEB-GPG-KEY-puppetlabs
