---

- name: PUPPET REDHAT | Add GPG key
  rpm_key:
    key: "{{ puppet_gpg_key }}"
    state: present

- name: PUPPET REDHAT | Add repository
  package:
    name: "{{ puppet_yum_rpm }}"
    state: present

- name: PUPPET REDHAT | Add repository for the development kit
  package:
    name: "{{ puppet_tools_yum_rpm }}"
    state: present
